### PR TITLE
Eclark/fix tests

### LINKED ISSUE #135: With zero abilities, arithmetic exception
When using the test warrior class, which has zero skills and abilities, when using the `/skills` command, the client crashes with a `java.lang.ArithmeticException: / by zero` error.

Fix by adding a catch for / 0 clause.

### LINKED ISSUE #137: Taking one item by name when there's more than one item
## To reproduce:
Enter the first cell of the game (0,1,0) when all items have generated. Take Excalibur's Third Attempt, by typing `/take excalibur's third attempt`
## Expected result:
item to be added to inventory, message `You take Excalibur's Third Attempt!'`
## Actual result:
Screen Shot 2019-11-17 at 6 36 07 PM

### PR DESCRIPTION
**Pull request by NotAnotherMetaTag**
Resolves #135 
Resolves #137 

Fixed two minor logic bugs

### CODE REVIEW

File: src/gameplay/commandServices/PlayerService.java [hunk 1]
```diff
@@ -346,7 +352,7 @@ private String takeItemFromInspectable(String param) {
 				outputBuilder.append(take.takeItemByNameFromInspectable(param));
 			}
 		} else {
-			return "You look around, but can't find anything by that name worth taking.";
+			//return "You look around, but can't find anything by that name worth taking.";
```
Comment (NotAnotherMetaTag) [inline src/gameplay/commandServices/PlayerService.java]: if this code is never reached, just remove the else block
